// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: pkg/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	AddedOnUnix    int64                  `protobuf:"varint,3,opt,name=added_on_unix,json=addedOnUnix,proto3" json:"added_on_unix,omitempty"`
	Size           int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ByteRangeStart int64                  `protobuf:"varint,5,opt,name=byte_range_start,json=byteRangeStart,proto3" json:"byte_range_start,omitempty"`
	ByteRangeEnd   int64                  `protobuf:"varint,6,opt,name=byte_range_end,json=byteRangeEnd,proto3" json:"byte_range_end,omitempty"`
	HasByteRange   bool                   `protobuf:"varint,7,opt,name=has_byte_range,json=hasByteRange,proto3" json:"has_byte_range,omitempty"`
	Deleted        bool                   `protobuf:"varint,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	InfoHash       string                 `protobuf:"bytes,9,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileProto) Reset() {
	*x = FileProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProto) ProtoMessage() {}

func (x *FileProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProto.ProtoReflect.Descriptor instead.
func (*FileProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *FileProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileProto) GetAddedOnUnix() int64 {
	if x != nil {
		return x.AddedOnUnix
	}
	return 0
}

func (x *FileProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileProto) GetByteRangeStart() int64 {
	if x != nil {
		return x.ByteRangeStart
	}
	return 0
}

func (x *FileProto) GetByteRangeEnd() int64 {
	if x != nil {
		return x.ByteRangeEnd
	}
	return 0
}

func (x *FileProto) GetHasByteRange() bool {
	if x != nil {
		return x.HasByteRange
	}
	return false
}

func (x *FileProto) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *FileProto) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type ProviderFileProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderFileProto) Reset() {
	*x = ProviderFileProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderFileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderFileProto) ProtoMessage() {}

func (x *ProviderFileProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderFileProto.ProtoReflect.Descriptor instead.
func (*ProviderFileProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderFileProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderFileProto) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ProviderFileProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ProviderEntryProto struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Provider         string                        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id               string                        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	AddedAtUnix      int64                         `protobuf:"varint,3,opt,name=added_at_unix,json=addedAtUnix,proto3" json:"added_at_unix,omitempty"`
	RemovedAtUnix    int64                         `protobuf:"varint,4,opt,name=removed_at_unix,json=removedAtUnix,proto3" json:"removed_at_unix,omitempty"`
	HasRemovedAt     bool                          `protobuf:"varint,5,opt,name=has_removed_at,json=hasRemovedAt,proto3" json:"has_removed_at,omitempty"`
	Status           string                        `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Progress         float64                       `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`
	Files            map[string]*ProviderFileProto `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DownloadedAtUnix int64                         `protobuf:"varint,9,opt,name=downloaded_at_unix,json=downloadedAtUnix,proto3" json:"downloaded_at_unix,omitempty"`
	HasDownloadedAt  bool                          `protobuf:"varint,10,opt,name=has_downloaded_at,json=hasDownloadedAt,proto3" json:"has_downloaded_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProviderEntryProto) Reset() {
	*x = ProviderEntryProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderEntryProto) ProtoMessage() {}

func (x *ProviderEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderEntryProto.ProtoReflect.Descriptor instead.
func (*ProviderEntryProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderEntryProto) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderEntryProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderEntryProto) GetAddedAtUnix() int64 {
	if x != nil {
		return x.AddedAtUnix
	}
	return 0
}

func (x *ProviderEntryProto) GetRemovedAtUnix() int64 {
	if x != nil {
		return x.RemovedAtUnix
	}
	return 0
}

func (x *ProviderEntryProto) GetHasRemovedAt() bool {
	if x != nil {
		return x.HasRemovedAt
	}
	return false
}

func (x *ProviderEntryProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProviderEntryProto) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProviderEntryProto) GetFiles() map[string]*ProviderFileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ProviderEntryProto) GetDownloadedAtUnix() int64 {
	if x != nil {
		return x.DownloadedAtUnix
	}
	return 0
}

func (x *ProviderEntryProto) GetHasDownloadedAt() bool {
	if x != nil {
		return x.HasDownloadedAt
	}
	return false
}

type EntryProto struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Protocol          string                         `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	InfoHash          string                         `protobuf:"bytes,2,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Name              string                         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OriginalFilename  string                         `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	Size              int64                          `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Bytes             int64                          `protobuf:"varint,6,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Magnet            string                         `protobuf:"bytes,7,opt,name=magnet,proto3" json:"magnet,omitempty"`
	IsDownloading     bool                           `protobuf:"varint,8,opt,name=is_downloading,json=isDownloading,proto3" json:"is_downloading,omitempty"`
	SizeDownloaded    int64                          `protobuf:"varint,9,opt,name=size_downloaded,json=sizeDownloaded,proto3" json:"size_downloaded,omitempty"`
	ActiveProvider    string                         `protobuf:"bytes,10,opt,name=active_provider,json=activeProvider,proto3" json:"active_provider,omitempty"`
	Providers         map[string]*ProviderEntryProto `protobuf:"bytes,11,rep,name=providers,proto3" json:"providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Files             map[string]*FileProto          `protobuf:"bytes,12,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State             string                         `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	Status            string                         `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Progress          float64                        `protobuf:"fixed64,15,opt,name=progress,proto3" json:"progress,omitempty"`
	Speed             int64                          `protobuf:"varint,16,opt,name=speed,proto3" json:"speed,omitempty"`
	Seeders           int32                          `protobuf:"varint,17,opt,name=seeders,proto3" json:"seeders,omitempty"`
	IsComplete        bool                           `protobuf:"varint,18,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	Bad               bool                           `protobuf:"varint,19,opt,name=bad,proto3" json:"bad,omitempty"`
	Category          string                         `protobuf:"bytes,20,opt,name=category,proto3" json:"category,omitempty"`
	Tags              []string                       `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	MountPath         string                         `protobuf:"bytes,22,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	SavePath          string                         `protobuf:"bytes,23,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	ContentPath       string                         `protobuf:"bytes,24,opt,name=content_path,json=contentPath,proto3" json:"content_path,omitempty"`
	AddedOnUnix       int64                          `protobuf:"varint,25,opt,name=added_on_unix,json=addedOnUnix,proto3" json:"added_on_unix,omitempty"`
	CreatedAtUnix     int64                          `protobuf:"varint,26,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix     int64                          `protobuf:"varint,27,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	CompletedAtUnix   int64                          `protobuf:"varint,28,opt,name=completed_at_unix,json=completedAtUnix,proto3" json:"completed_at_unix,omitempty"`
	HasCompletedAt    bool                           `protobuf:"varint,29,opt,name=has_completed_at,json=hasCompletedAt,proto3" json:"has_completed_at,omitempty"`
	ImportedAtUnix    int64                          `protobuf:"varint,30,opt,name=imported_at_unix,json=importedAtUnix,proto3" json:"imported_at_unix,omitempty"`
	HasImportedAt     bool                           `protobuf:"varint,31,opt,name=has_imported_at,json=hasImportedAt,proto3" json:"has_imported_at,omitempty"`
	Action            string                         `protobuf:"bytes,32,opt,name=action,proto3" json:"action,omitempty"`
	DownloadUncached  bool                           `protobuf:"varint,33,opt,name=download_uncached,json=downloadUncached,proto3" json:"download_uncached,omitempty"`
	CallbackUrl       string                         `protobuf:"bytes,34,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	SkipMultiSeason   bool                           `protobuf:"varint,35,opt,name=skip_multi_season,json=skipMultiSeason,proto3" json:"skip_multi_season,omitempty"`
	LastError         string                         `protobuf:"bytes,36,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ErrorCount        int32                          `protobuf:"varint,37,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	LastErrorTimeUnix int64                          `protobuf:"varint,38,opt,name=last_error_time_unix,json=lastErrorTimeUnix,proto3" json:"last_error_time_unix,omitempty"`
	HasLastErrorTime  bool                           `protobuf:"varint,39,opt,name=has_last_error_time,json=hasLastErrorTime,proto3" json:"has_last_error_time,omitempty"`
	RmTrackerUrls     bool                           `protobuf:"varint,40,opt,name=rm_tracker_urls,json=rmTrackerUrls,proto3" json:"rm_tracker_urls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EntryProto) Reset() {
	*x = EntryProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryProto) ProtoMessage() {}

func (x *EntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryProto.ProtoReflect.Descriptor instead.
func (*EntryProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *EntryProto) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *EntryProto) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *EntryProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntryProto) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *EntryProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EntryProto) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *EntryProto) GetMagnet() string {
	if x != nil {
		return x.Magnet
	}
	return ""
}

func (x *EntryProto) GetIsDownloading() bool {
	if x != nil {
		return x.IsDownloading
	}
	return false
}

func (x *EntryProto) GetSizeDownloaded() int64 {
	if x != nil {
		return x.SizeDownloaded
	}
	return 0
}

func (x *EntryProto) GetActiveProvider() string {
	if x != nil {
		return x.ActiveProvider
	}
	return ""
}

func (x *EntryProto) GetProviders() map[string]*ProviderEntryProto {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *EntryProto) GetFiles() map[string]*FileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *EntryProto) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EntryProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EntryProto) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *EntryProto) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *EntryProto) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *EntryProto) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *EntryProto) GetBad() bool {
	if x != nil {
		return x.Bad
	}
	return false
}

func (x *EntryProto) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EntryProto) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntryProto) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *EntryProto) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *EntryProto) GetContentPath() string {
	if x != nil {
		return x.ContentPath
	}
	return ""
}

func (x *EntryProto) GetAddedOnUnix() int64 {
	if x != nil {
		return x.AddedOnUnix
	}
	return 0
}

func (x *EntryProto) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *EntryProto) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *EntryProto) GetCompletedAtUnix() int64 {
	if x != nil {
		return x.CompletedAtUnix
	}
	return 0
}

func (x *EntryProto) GetHasCompletedAt() bool {
	if x != nil {
		return x.HasCompletedAt
	}
	return false
}

func (x *EntryProto) GetImportedAtUnix() int64 {
	if x != nil {
		return x.ImportedAtUnix
	}
	return 0
}

func (x *EntryProto) GetHasImportedAt() bool {
	if x != nil {
		return x.HasImportedAt
	}
	return false
}

func (x *EntryProto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EntryProto) GetDownloadUncached() bool {
	if x != nil {
		return x.DownloadUncached
	}
	return false
}

func (x *EntryProto) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *EntryProto) GetSkipMultiSeason() bool {
	if x != nil {
		return x.SkipMultiSeason
	}
	return false
}

func (x *EntryProto) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *EntryProto) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *EntryProto) GetLastErrorTimeUnix() int64 {
	if x != nil {
		return x.LastErrorTimeUnix
	}
	return 0
}

func (x *EntryProto) GetHasLastErrorTime() bool {
	if x != nil {
		return x.HasLastErrorTime
	}
	return false
}

func (x *EntryProto) GetRmTrackerUrls() bool {
	if x != nil {
		return x.RmTrackerUrls
	}
	return false
}

type EntryItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files         map[string]*FileProto  `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryItemProto) Reset() {
	*x = EntryItemProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryItemProto) ProtoMessage() {}

func (x *EntryItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryItemProto.ProtoReflect.Descriptor instead.
func (*EntryItemProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *EntryItemProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntryItemProto) GetFiles() map[string]*FileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *EntryItemProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ContentFileProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	EpisodeId     int32                  `protobuf:"varint,4,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	FileId        int32                  `protobuf:"varint,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TargetPath    string                 `protobuf:"bytes,6,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	IsSymlink     bool                   `protobuf:"varint,7,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`
	IsBroken      bool                   `protobuf:"varint,8,opt,name=is_broken,json=isBroken,proto3" json:"is_broken,omitempty"`
	SeasonNumber  int32                  `protobuf:"varint,9,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	Processed     bool                   `protobuf:"varint,10,opt,name=processed,proto3" json:"processed,omitempty"`
	Size          int64                  `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFileProto) Reset() {
	*x = ContentFileProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFileProto) ProtoMessage() {}

func (x *ContentFileProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFileProto.ProtoReflect.Descriptor instead.
func (*ContentFileProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ContentFileProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentFileProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ContentFileProto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentFileProto) GetEpisodeId() int32 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *ContentFileProto) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *ContentFileProto) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ContentFileProto) GetIsSymlink() bool {
	if x != nil {
		return x.IsSymlink
	}
	return false
}

func (x *ContentFileProto) GetIsBroken() bool {
	if x != nil {
		return x.IsBroken
	}
	return false
}

func (x *ContentFileProto) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *ContentFileProto) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *ContentFileProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type JobProto struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Id              string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arrs            []string                     `protobuf:"bytes,2,rep,name=arrs,proto3" json:"arrs,omitempty"`
	MediaIds        []string                     `protobuf:"bytes,3,rep,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	StartedAtUnix   int64                        `protobuf:"varint,4,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	BrokenItems     map[string]*BrokenItemsProto `protobuf:"bytes,5,rep,name=broken_items,json=brokenItems,proto3" json:"broken_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status          string                       `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CompletedAtUnix int64                        `protobuf:"varint,7,opt,name=completed_at_unix,json=completedAtUnix,proto3" json:"completed_at_unix,omitempty"`
	FailedAtUnix    int64                        `protobuf:"varint,8,opt,name=failed_at_unix,json=failedAtUnix,proto3" json:"failed_at_unix,omitempty"`
	AutoProcess     bool                         `protobuf:"varint,9,opt,name=auto_process,json=autoProcess,proto3" json:"auto_process,omitempty"`
	Recurrent       bool                         `protobuf:"varint,10,opt,name=recurrent,proto3" json:"recurrent,omitempty"`
	Error           string                       `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobProto) Reset() {
	*x = JobProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProto) ProtoMessage() {}

func (x *JobProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProto.ProtoReflect.Descriptor instead.
func (*JobProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{6}
}

func (x *JobProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobProto) GetArrs() []string {
	if x != nil {
		return x.Arrs
	}
	return nil
}

func (x *JobProto) GetMediaIds() []string {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *JobProto) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *JobProto) GetBrokenItems() map[string]*BrokenItemsProto {
	if x != nil {
		return x.BrokenItems
	}
	return nil
}

func (x *JobProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobProto) GetCompletedAtUnix() int64 {
	if x != nil {
		return x.CompletedAtUnix
	}
	return 0
}

func (x *JobProto) GetFailedAtUnix() int64 {
	if x != nil {
		return x.FailedAtUnix
	}
	return 0
}

func (x *JobProto) GetAutoProcess() bool {
	if x != nil {
		return x.AutoProcess
	}
	return false
}

func (x *JobProto) GetRecurrent() bool {
	if x != nil {
		return x.Recurrent
	}
	return false
}

func (x *JobProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BrokenItemsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ContentFileProto    `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokenItemsProto) Reset() {
	*x = BrokenItemsProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenItemsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenItemsProto) ProtoMessage() {}

func (x *BrokenItemsProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenItemsProto.ProtoReflect.Descriptor instead.
func (*BrokenItemsProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *BrokenItemsProto) GetFiles() []*ContentFileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

type SwitcherJobProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InfoHash        string                 `protobuf:"bytes,2,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	SourceProvider  string                 `protobuf:"bytes,3,opt,name=source_provider,json=sourceProvider,proto3" json:"source_provider,omitempty"`
	TargetProvider  string                 `protobuf:"bytes,4,opt,name=target_provider,json=targetProvider,proto3" json:"target_provider,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Progress        float64                `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Error           string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	CompletedAtUnix int64                  `protobuf:"varint,9,opt,name=completed_at_unix,json=completedAtUnix,proto3" json:"completed_at_unix,omitempty"`
	HasCompletedAt  bool                   `protobuf:"varint,10,opt,name=has_completed_at,json=hasCompletedAt,proto3" json:"has_completed_at,omitempty"`
	KeepOld         bool                   `protobuf:"varint,11,opt,name=keep_old,json=keepOld,proto3" json:"keep_old,omitempty"`
	WaitComplete    bool                   `protobuf:"varint,12,opt,name=wait_complete,json=waitComplete,proto3" json:"wait_complete,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SwitcherJobProto) Reset() {
	*x = SwitcherJobProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitcherJobProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitcherJobProto) ProtoMessage() {}

func (x *SwitcherJobProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitcherJobProto.ProtoReflect.Descriptor instead.
func (*SwitcherJobProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{8}
}

func (x *SwitcherJobProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SwitcherJobProto) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *SwitcherJobProto) GetSourceProvider() string {
	if x != nil {
		return x.SourceProvider
	}
	return ""
}

func (x *SwitcherJobProto) GetTargetProvider() string {
	if x != nil {
		return x.TargetProvider
	}
	return ""
}

func (x *SwitcherJobProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwitcherJobProto) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SwitcherJobProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SwitcherJobProto) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SwitcherJobProto) GetCompletedAtUnix() int64 {
	if x != nil {
		return x.CompletedAtUnix
	}
	return 0
}

func (x *SwitcherJobProto) GetHasCompletedAt() bool {
	if x != nil {
		return x.HasCompletedAt
	}
	return false
}

func (x *SwitcherJobProto) GetKeepOld() bool {
	if x != nil {
		return x.KeepOld
	}
	return false
}

func (x *SwitcherJobProto) GetWaitComplete() bool {
	if x != nil {
		return x.WaitComplete
	}
	return false
}

type SystemMigrationStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Completed     int32                  `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Errors        int32                  `protobuf:"varint,4,opt,name=errors,proto3" json:"errors,omitempty"`
	StartedAtUnix int64                  `protobuf:"varint,5,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,6,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	ErrorList     []string               `protobuf:"bytes,7,rep,name=error_list,json=errorList,proto3" json:"error_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMigrationStatusProto) Reset() {
	*x = SystemMigrationStatusProto{}
	mi := &file_pkg_storage_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMigrationStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMigrationStatusProto) ProtoMessage() {}

func (x *SystemMigrationStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMigrationStatusProto.ProtoReflect.Descriptor instead.
func (*SystemMigrationStatusProto) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{9}
}

func (x *SystemMigrationStatusProto) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *SystemMigrationStatusProto) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SystemMigrationStatusProto) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *SystemMigrationStatusProto) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *SystemMigrationStatusProto) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *SystemMigrationStatusProto) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *SystemMigrationStatusProto) GetErrorList() []string {
	if x != nil {
		return x.ErrorList
	}
	return nil
}

var File_pkg_storage_storage_proto protoreflect.FileDescriptor

const file_pkg_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/storage/storage.proto\x12\astorage\"\x98\x02\n" +
	"\tFileProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\"\n" +
	"\radded_on_unix\x18\x03 \x01(\x03R\vaddedOnUnix\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12(\n" +
	"\x10byte_range_start\x18\x05 \x01(\x03R\x0ebyteRangeStart\x12$\n" +
	"\x0ebyte_range_end\x18\x06 \x01(\x03R\fbyteRangeEnd\x12$\n" +
	"\x0ehas_byte_range\x18\a \x01(\bR\fhasByteRange\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\x12\x1b\n" +
	"\tinfo_hash\x18\t \x01(\tR\binfoHash\"K\n" +
	"\x11ProviderFileProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xd4\x03\n" +
	"\x12ProviderEntryProto\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\"\n" +
	"\radded_at_unix\x18\x03 \x01(\x03R\vaddedAtUnix\x12&\n" +
	"\x0fremoved_at_unix\x18\x04 \x01(\x03R\rremovedAtUnix\x12$\n" +
	"\x0ehas_removed_at\x18\x05 \x01(\bR\fhasRemovedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x12<\n" +
	"\x05files\x18\b \x03(\v2&.storage.ProviderEntryProto.FilesEntryR\x05files\x12,\n" +
	"\x12downloaded_at_unix\x18\t \x01(\x03R\x10downloadedAtUnix\x12*\n" +
	"\x11has_downloaded_at\x18\n" +
	" \x01(\bR\x0fhasDownloadedAt\x1aT\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.storage.ProviderFileProtoR\x05value:\x028\x01\"\x96\f\n" +
	"\n" +
	"EntryProto\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tinfo_hash\x18\x02 \x01(\tR\binfoHash\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x14\n" +
	"\x05bytes\x18\x06 \x01(\x03R\x05bytes\x12\x16\n" +
	"\x06magnet\x18\a \x01(\tR\x06magnet\x12%\n" +
	"\x0eis_downloading\x18\b \x01(\bR\risDownloading\x12'\n" +
	"\x0fsize_downloaded\x18\t \x01(\x03R\x0esizeDownloaded\x12'\n" +
	"\x0factive_provider\x18\n" +
	" \x01(\tR\x0eactiveProvider\x12@\n" +
	"\tproviders\x18\v \x03(\v2\".storage.EntryProto.ProvidersEntryR\tproviders\x124\n" +
	"\x05files\x18\f \x03(\v2\x1e.storage.EntryProto.FilesEntryR\x05files\x12\x14\n" +
	"\x05state\x18\r \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x0f \x01(\x01R\bprogress\x12\x14\n" +
	"\x05speed\x18\x10 \x01(\x03R\x05speed\x12\x18\n" +
	"\aseeders\x18\x11 \x01(\x05R\aseeders\x12\x1f\n" +
	"\vis_complete\x18\x12 \x01(\bR\n" +
	"isComplete\x12\x10\n" +
	"\x03bad\x18\x13 \x01(\bR\x03bad\x12\x1a\n" +
	"\bcategory\x18\x14 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x15 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x16 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tsave_path\x18\x17 \x01(\tR\bsavePath\x12!\n" +
	"\fcontent_path\x18\x18 \x01(\tR\vcontentPath\x12\"\n" +
	"\radded_on_unix\x18\x19 \x01(\x03R\vaddedOnUnix\x12&\n" +
	"\x0fcreated_at_unix\x18\x1a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x1b \x01(\x03R\rupdatedAtUnix\x12*\n" +
	"\x11completed_at_unix\x18\x1c \x01(\x03R\x0fcompletedAtUnix\x12(\n" +
	"\x10has_completed_at\x18\x1d \x01(\bR\x0ehasCompletedAt\x12(\n" +
	"\x10imported_at_unix\x18\x1e \x01(\x03R\x0eimportedAtUnix\x12&\n" +
	"\x0fhas_imported_at\x18\x1f \x01(\bR\rhasImportedAt\x12\x16\n" +
	"\x06action\x18  \x01(\tR\x06action\x12+\n" +
	"\x11download_uncached\x18! \x01(\bR\x10downloadUncached\x12!\n" +
	"\fcallback_url\x18\" \x01(\tR\vcallbackUrl\x12*\n" +
	"\x11skip_multi_season\x18# \x01(\bR\x0fskipMultiSeason\x12\x1d\n" +
	"\n" +
	"last_error\x18$ \x01(\tR\tlastError\x12\x1f\n" +
	"\verror_count\x18% \x01(\x05R\n" +
	"errorCount\x12/\n" +
	"\x14last_error_time_unix\x18& \x01(\x03R\x11lastErrorTimeUnix\x12-\n" +
	"\x13has_last_error_time\x18' \x01(\bR\x10hasLastErrorTime\x12&\n" +
	"\x0frm_tracker_urls\x18( \x01(\bR\rrmTrackerUrls\x1aY\n" +
	"\x0eProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.storage.ProviderEntryProtoR\x05value:\x028\x01\x1aL\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.storage.FileProtoR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x0eEntryItemProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x05files\x18\x02 \x03(\v2\".storage.EntryItemProto.FilesEntryR\x05files\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x1aL\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.storage.FileProtoR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x10ContentFileProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x04 \x01(\x05R\tepisodeId\x12\x17\n" +
	"\afile_id\x18\x05 \x01(\x05R\x06fileId\x12\x1f\n" +
	"\vtarget_path\x18\x06 \x01(\tR\n" +
	"targetPath\x12\x1d\n" +
	"\n" +
	"is_symlink\x18\a \x01(\bR\tisSymlink\x12\x1b\n" +
	"\tis_broken\x18\b \x01(\bR\bisBroken\x12#\n" +
	"\rseason_number\x18\t \x01(\x05R\fseasonNumber\x12\x1c\n" +
	"\tprocessed\x18\n" +
	" \x01(\bR\tprocessed\x12\x12\n" +
	"\x04size\x18\v \x01(\x03R\x04size\"\xd6\x03\n" +
	"\bJobProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04arrs\x18\x02 \x03(\tR\x04arrs\x12\x1b\n" +
	"\tmedia_ids\x18\x03 \x03(\tR\bmediaIds\x12&\n" +
	"\x0fstarted_at_unix\x18\x04 \x01(\x03R\rstartedAtUnix\x12E\n" +
	"\fbroken_items\x18\x05 \x03(\v2\".storage.JobProto.BrokenItemsEntryR\vbrokenItems\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12*\n" +
	"\x11completed_at_unix\x18\a \x01(\x03R\x0fcompletedAtUnix\x12$\n" +
	"\x0efailed_at_unix\x18\b \x01(\x03R\ffailedAtUnix\x12!\n" +
	"\fauto_process\x18\t \x01(\bR\vautoProcess\x12\x1c\n" +
	"\trecurrent\x18\n" +
	" \x01(\bR\trecurrent\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x1aY\n" +
	"\x10BrokenItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.storage.BrokenItemsProtoR\x05value:\x028\x01\"C\n" +
	"\x10BrokenItemsProto\x12/\n" +
	"\x05files\x18\x01 \x03(\v2\x19.storage.ContentFileProtoR\x05files\"\x99\x03\n" +
	"\x10SwitcherJobProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tinfo_hash\x18\x02 \x01(\tR\binfoHash\x12'\n" +
	"\x0fsource_provider\x18\x03 \x01(\tR\x0esourceProvider\x12'\n" +
	"\x0ftarget_provider\x18\x04 \x01(\tR\x0etargetProvider\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12*\n" +
	"\x11completed_at_unix\x18\t \x01(\x03R\x0fcompletedAtUnix\x12(\n" +
	"\x10has_completed_at\x18\n" +
	" \x01(\bR\x0ehasCompletedAt\x12\x19\n" +
	"\bkeep_old\x18\v \x01(\bR\akeepOld\x12#\n" +
	"\rwait_complete\x18\f \x01(\bR\fwaitComplete\"\xf1\x01\n" +
	"\x1aSystemMigrationStatusProto\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x05R\tcompleted\x12\x16\n" +
	"\x06errors\x18\x04 \x01(\x05R\x06errors\x12&\n" +
	"\x0fstarted_at_unix\x18\x05 \x01(\x03R\rstartedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x06 \x01(\x03R\rupdatedAtUnix\x12\x1d\n" +
	"\n" +
	"error_list\x18\a \x03(\tR\terrorListB-Z+github.com/sirrobot01/decypharr/pkg/storageb\x06proto3"

var (
	file_pkg_storage_storage_proto_rawDescOnce sync.Once
	file_pkg_storage_storage_proto_rawDescData []byte
)

func file_pkg_storage_storage_proto_rawDescGZIP() []byte {
	file_pkg_storage_storage_proto_rawDescOnce.Do(func() {
		file_pkg_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_storage_storage_proto_rawDesc), len(file_pkg_storage_storage_proto_rawDesc)))
	})
	return file_pkg_storage_storage_proto_rawDescData
}

var file_pkg_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_storage_storage_proto_goTypes = []any{
	(*FileProto)(nil),                  // 0: storage.FileProto
	(*ProviderFileProto)(nil),          // 1: storage.ProviderFileProto
	(*ProviderEntryProto)(nil),         // 2: storage.ProviderEntryProto
	(*EntryProto)(nil),                 // 3: storage.EntryProto
	(*EntryItemProto)(nil),             // 4: storage.EntryItemProto
	(*ContentFileProto)(nil),           // 5: storage.ContentFileProto
	(*JobProto)(nil),                   // 6: storage.JobProto
	(*BrokenItemsProto)(nil),           // 7: storage.BrokenItemsProto
	(*SwitcherJobProto)(nil),           // 8: storage.SwitcherJobProto
	(*SystemMigrationStatusProto)(nil), // 9: storage.SystemMigrationStatusProto
	nil,                                // 10: storage.ProviderEntryProto.FilesEntry
	nil,                                // 11: storage.EntryProto.ProvidersEntry
	nil,                                // 12: storage.EntryProto.FilesEntry
	nil,                                // 13: storage.EntryItemProto.FilesEntry
	nil,                                // 14: storage.JobProto.BrokenItemsEntry
}
var file_pkg_storage_storage_proto_depIdxs = []int32{
	10, // 0: storage.ProviderEntryProto.files:type_name -> storage.ProviderEntryProto.FilesEntry
	11, // 1: storage.EntryProto.providers:type_name -> storage.EntryProto.ProvidersEntry
	12, // 2: storage.EntryProto.files:type_name -> storage.EntryProto.FilesEntry
	13, // 3: storage.EntryItemProto.files:type_name -> storage.EntryItemProto.FilesEntry
	14, // 4: storage.JobProto.broken_items:type_name -> storage.JobProto.BrokenItemsEntry
	5,  // 5: storage.BrokenItemsProto.files:type_name -> storage.ContentFileProto
	1,  // 6: storage.ProviderEntryProto.FilesEntry.value:type_name -> storage.ProviderFileProto
	2,  // 7: storage.EntryProto.ProvidersEntry.value:type_name -> storage.ProviderEntryProto
	0,  // 8: storage.EntryProto.FilesEntry.value:type_name -> storage.FileProto
	0,  // 9: storage.EntryItemProto.FilesEntry.value:type_name -> storage.FileProto
	7,  // 10: storage.JobProto.BrokenItemsEntry.value:type_name -> storage.BrokenItemsProto
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_storage_storage_proto_init() }
func file_pkg_storage_storage_proto_init() {
	if File_pkg_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_storage_storage_proto_rawDesc), len(file_pkg_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_storage_storage_proto_goTypes,
		DependencyIndexes: file_pkg_storage_storage_proto_depIdxs,
		MessageInfos:      file_pkg_storage_storage_proto_msgTypes,
	}.Build()
	File_pkg_storage_storage_proto = out.File
	file_pkg_storage_storage_proto_goTypes = nil
	file_pkg_storage_storage_proto_depIdxs = nil
}
